
############################################################################
### USER PARAMETERS ########################################################
############################################################################

## example pheno file. See the example file sample.phenotype.txt  in the data directory
pheno-file:

## output directory to be defined by the user
outdir: 

## directory for temporary files, by default the user's ephemeral
tempdir: /rds/general/user/$USER/ephemeral/

## True or False. If true, temporary files are deleted at the end of the run
temp-delete: True

## TODO check why this syntax is used, otherwise simplyfy
## models. syntax: COV_i=[cat_cov1,...,cat_covn];[quant_cov1,...,quant_covn]
cov-1: "Sex,Center;Age,PC1,PC2,PC3,PC4"

## phenotypes. syntax: PHENO_j=phenotype;[excl_indivs_file]
pheno-1: "log_Mean_cIMT_Max;"

## file listing samples to remove, leave empty if not needed
remove-file:

min-maf: 0.01
min-info: 0.1


############################################################################
### INPUT DATA ########################################################
############################################################################

sample-file: /rds/general/project/medbio-epiukb-archive-2018/live/UKB_pheno/UKBdownloads/ukb23_imp_chr21_v2_s487406.sample
fam-file: /rds/general/project/medbio-epiukb-archive-2018/live/UKB_pheno/UKBdownloads/ukb23_cal_chr21_v2_s488374.fam


### UK Biobank release version
# sdata_12072017: initial 2017 release (v2), points to files in release_12072017, constrained to HRC-panel
# sdata_12032018: fixed 2018 release (v3), points to files in release_12032018
data-dir: /rds/general/project/uk-biobank-2017/live/reference/sdata_latest

### software and database versions
# sresources_28032018: BOLT 2.3, PLINK2 1_Oct_2017
sresources: /rds/general/project/uk-biobank-2017/live/sresources_latest

############################################################################
### ONLY CHANGE BELOW THIS LINE IF YOU ARE SURE ABOUT WHAT YOU ARE DOING ###
############################################################################

### additional BOLT-LMM output
# output betas for risk prediction (--predBetasFile flag); set to yes to get betas under ranges_betas/
get_betas: no

## TODO commented out, if else has to be implemented in the script
### binaries and auxiliary files
# if [[ $SDATA = *"sdata_12072017"* ]]; then
# 	SNPS_TO_KEEP=${SRESOURCES}/annotation/snps_HRC_minus_discordant/HRC_minus_discordant.snplist
# else
# 	SNPS_TO_KEEP=${SRESOURCES}/annotation/snps_all/all_imp_minus_discordant.snplist
# fi


ldscore-file: /rds/general/project/uk-biobank-2017/live/sresources_latest/bin/BOLT-LMM_v2.3/tables/LDSCORE.1000G_EUR.tab.gz

### filtering parameters for the selection of core SNPs
thr-maf: 0.05
thr-geno: 0.015
thr-hwe: 1e-6

### execution parameters: 2x10^6 snps per chunk
chunksize: 2000000
ncpus: 4 # per run-bolt job

## comma-separated list of chromosomes, if commented out the default set of 1..22 will be used
chr-list: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22

imp-base: ukb_imp_chr
gen-base: ukb_gen_chr

module-init: /usr/share/Modules/init/python.py 

## comma separated list of modules
module-list: plink/1.90p, bolt-lmm/2.3, bgenix/2017-05-15
