
############################################################################
### USER PARAMETERS ########################################################
############################################################################

## TODO check why this syntax is used, otherwise simplyfy
### models. syntax: COV_i=[cat_cov1,...,cat_covn];[quant_cov1,...,quant_covn]
cov-1: "Sex,Center;Age,PC1,PC2,PC3,PC4"

### phenotypes. syntax: PHENO_j=phenotype;[excl_indivs_file]
pheno-1: "log_Mean_cIMT_Max;"

### input

sample-file: /rds/general/project/medbio-epiukb-archive-2018/live/UKB_pheno/UKBdownloads/ukb23_imp_chr21_v2_s487406.sample
pheno-file: /rds/general/user/gotto/home/project/bolt-lmm-pipeline/bolt-lmm-pipeline/data/sample.phenotype.txt
fam-file: /rds/general/project/medbio-epiukb-archive-2018/live/UKB_pheno/UKBdownloads/ukb23_cal_chr21_v2_s488374.fam

### output
### TODO user defined
outdir: /rds/general/user/gotto/ephemeral/test/bolt-lmm/test-pipeline-5/output
min-maf: 0.01
min-info: 0.1

### UK Biobank release version
# sdata_12072017: initial 2017 release (v2), points to files in release_12072017, constrained to HRC-panel
# sdata_12032018: fixed 2018 release (v3), points to files in release_12032018
data-dir: /rds/general/project/uk-biobank-2017/live/reference/sdata_latest

### software and database versions
# sresources_28032018: BOLT 2.3, PLINK2 1_Oct_2017
sresources: /rds/general/project/uk-biobank-2017/live/sresources_latest

############################################################################
### ONLY CHANGE BELOW THIS LINE IF YOU ARE SURE ABOUT WHAT YOU ARE DOING ###
############################################################################

### additional BOLT-LMM output
# output betas for risk prediction (--predBetasFile flag); set to yes to get betas under ranges_betas/
get_betas: no

## TODO commented out, if else has to be implemented in the script
### binaries and auxiliary files
# if [[ $SDATA = *"sdata_12072017"* ]]; then
# 	SNPS_TO_KEEP=${SRESOURCES}/annotation/snps_HRC_minus_discordant/HRC_minus_discordant.snplist
# else
# 	SNPS_TO_KEEP=${SRESOURCES}/annotation/snps_all/all_imp_minus_discordant.snplist
# fi


ldscore-file: /rds/general/project/uk-biobank-2017/live/sresources_latest/bin/BOLT-LMM_v2.3/tables/LDSCORE.1000G_EUR.tab.gz
# BINPATH=${SRESOURCES}/bin/

### filtering parameters for the selection of core SNPs
thr-maf: 0.05
thr-geno: 0.015
thr-hwe: 1e-6

### execution parameters
chunksize: 5000000
nnodes: 1 # per job

## comma-separated list of chromosomes, if commented out the default set of 1..22 will be used
chr-list: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22

# DATAPATH=${SDATA}/
# BASENAMES=$(eval echo ukb_imp_chr{${CHRS// /,}})
# GBASENAMES=$(eval echo ukb_gen_chr{${CHRS// /,}})
imp-base: ukb_imp_chr
gen-base: ukb_gen_chr

module-init: /usr/share/Modules/init/python.py 

## comma separated list of modules
module-list: plink/1.90p

